@startuml
actor "Document Administrator" as DA
participant "Document Source" as DS
participant "Document Registry" as DReg

DA -> DS: Identify need to deprecate existing document
DA -> DReg: Send request to deprecate a document
DReg -> DReg: Process deprecation request
DReg -> DReg: Update availabilityStatus to 'deprecated' for document
DReg -> DA: Return successful response
@enduml
